#!/usr/bin/env bash
#
# bootstrap.sh — one-shot installer for the cloud dispatcher box.
#
# Run on a fresh Ubuntu 24.04 EC2 as root. Idempotent — re-running will
# update the repo, rewrite systemd units, and restart services without
# regenerating the auth token.
#
# Usage:
#   sudo bash bootstrap.sh <hostname> [<github-clone-url>]
#
#   <hostname>          The public hostname Caddy will request a TLS cert
#                       for. Either a sslip.io name like
#                       `mine.3-14-15-92.sslip.io` or a real domain you
#                       control (DNS A record must already point at this
#                       box's public IP).
#   <github-clone-url>  Optional. Defaults to the upstream repo URL below.
#
set -euo pipefail

HOSTNAME_ARG="${1:-}"
REPO_URL="${2:-https://github.com/bonro001/retirement-calculator.git}"

if [[ -z "$HOSTNAME_ARG" ]]; then
  echo "usage: sudo bash bootstrap.sh <hostname> [<repo-url>]" >&2
  exit 1
fi
if [[ $EUID -ne 0 ]]; then
  echo "must run as root (use sudo)" >&2
  exit 1
fi

echo "[1/8] apt update + base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl git debian-keyring debian-archive-keyring \
  apt-transport-https openssl

echo "[2/8] Node 22 (NodeSource repo)"
if ! command -v node >/dev/null || [[ "$(node -v 2>/dev/null)" != v22* ]]; then
  curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
  apt-get install -y -qq nodejs
fi
node -v

echo "[3/8] Caddy"
if ! command -v caddy >/dev/null; then
  curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/gpg.key \
    | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -fsSL https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt \
    | tee /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -qq
  apt-get install -y -qq caddy
fi

echo "[4/8] cluster user + dirs"
if ! id cluster >/dev/null 2>&1; then
  useradd --system --create-home --shell /usr/sbin/nologin cluster
fi
install -d -o cluster -g cluster -m 0755 /opt/retirement-calculator
install -d -o cluster -g cluster -m 0700 /var/lib/cluster
install -d -o cluster -g cluster -m 0755 /var/lib/cluster/data

echo "[5/8] clone or update repo"
if [[ ! -d /opt/retirement-calculator/.git ]]; then
  sudo -u cluster git clone --depth 50 "$REPO_URL" /opt/retirement-calculator
else
  sudo -u cluster git -C /opt/retirement-calculator fetch --depth 50 origin
  sudo -u cluster git -C /opt/retirement-calculator reset --hard origin/main
fi
sudo -u cluster bash -c 'cd /opt/retirement-calculator && npm ci'

echo "[6/8] /etc/default/cluster (preserves existing token)"
ENVFILE=/etc/default/cluster
if [[ -f "$ENVFILE" ]]; then
  echo "  existing $ENVFILE found — leaving CLUSTER_AUTH_TOKEN untouched"
else
  TOKEN="$(openssl rand -hex 32)"
  install -o root -g cluster -m 0640 /dev/stdin "$ENVFILE" <<EOF
# Generated by bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
CLUSTER_AUTH_TOKEN=$TOKEN
DISPATCHER_PORT=8765
CLUSTER_DATA_DIR=/var/lib/cluster/data
DISPATCHER_URL=ws://localhost:8765
HOST_WORKERS=4
HOST_PERF_CLASS=x86-modern
EOF
  echo "  generated new token"
fi

echo "[7/8] systemd units + Caddyfile"
DEPLOY=/opt/retirement-calculator/deploy/cloud
install -o root -g root -m 0644 \
  "$DEPLOY/systemd/cluster-dispatcher.service" \
  /etc/systemd/system/cluster-dispatcher.service
install -o root -g root -m 0644 \
  "$DEPLOY/systemd/cluster-host@.service" \
  /etc/systemd/system/cluster-host@.service

# Substitute the hostname into the Caddyfile.
sed "s|\${HOSTNAME}|$HOSTNAME_ARG|g" "$DEPLOY/Caddyfile" \
  > /etc/caddy/Caddyfile
chmod 0644 /etc/caddy/Caddyfile

systemctl daemon-reload

echo "[8/8] enable + start"
# Decide host count from vCPUs: leave 2 cores for OS + dispatcher,
# split the rest into hosts of HOST_WORKERS=4 each (matches env).
VCPU="$(nproc)"
HOSTS=$(( (VCPU - 2) / 4 ))
if (( HOSTS < 1 )); then HOSTS=1; fi
echo "  vCPUs=$VCPU → enabling $HOSTS host process(es)"

systemctl enable --now caddy cluster-dispatcher
HOST_UNITS=()
for i in $(seq 1 "$HOSTS"); do HOST_UNITS+=("cluster-host@${i}"); done
systemctl enable --now "${HOST_UNITS[@]}"

echo
echo "Done. Verify:"
echo "  systemctl status cluster-dispatcher --no-pager"
echo "  systemctl status 'cluster-host@*' --no-pager"
echo "  curl https://$HOSTNAME_ARG/health"
echo
if [[ -z "${TOKEN:-}" ]]; then
  TOKEN="$(grep ^CLUSTER_AUTH_TOKEN= /etc/default/cluster | cut -d= -f2)"
fi
echo "Add to your local .env (or .env.production):"
echo "  VITE_DISPATCHER_URL=wss://$HOSTNAME_ARG"
echo "  VITE_DISPATCHER_TOKEN=$TOKEN"
